########
# Site #
########

site_name: MkDocs + MkDocstrings Testing
site_description: Automatic documentation from sources, using MkDocstrings with MkDocs Material.
# site_url: ...
# repo_url: ...
# repo_name: ...
site_dir: ../../site
copyright: Copyright &copy; 2024 Laurens van der Tas

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

##############
# Navigation #
##############

nav:
  - Home:
      - Overview: index.md
  - API Reference: reference/

#########
# Theme #
#########

theme:
  name: material
  # logo: logo.svg
  custom_dir: docs/.overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to system preference

extra_css:
  - css/mkdocstrings.css
  - css/style.css

#######################
# Markdown Extensions #
#######################

markdown_extensions:
  - attr_list
  - admonition
  - callouts
  - footnotes
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.magiclink
  - pymdownx.snippets:
      base_path: [!relative $config_dir]
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: "¤"

###########
# Plugins #
###########

plugins:
  - offline:
      enabled: !ENV [OFFLINE, false]
  - autorefs
  - search
  - markdown-exec:
      ansi: required
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      # custom_templates: templates
      # default_handler: python
      # enable_inventory: true
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
            - https://installer.readthedocs.io/en/stable/objects.inv
            - https://mkdocstrings.github.io/autorefs/objects.inv
          paths: [src]
          options:
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: list
            filters: ["!^_"]
            heading_level: 1
            inherited_members: true
            merge_init_into_class: false
            separate_signature: true
            show_root_heading: true
            show_root_full_path: true
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true
            show_submodules: true
            group_by_category: true
            show_if_no_docstring: true
  - minify:
      minify_html: !ENV [DEPLOY, false]

#########
# EXTRA #
#########

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/LPvdT
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/lpvdt/
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/mkdocstrings/
