########
# Site #
########

site_name: MkDocs + MkDocstrings Testing
site_description: Automatic documentation from sources, using MkDocstrings with MkDocs Material.
site_url: https://LPvdT.github.io/mkdocs-demo
repo_url: https://github.com/LPvdT/mkdocs-demo
repo_name: mkdocs-demo
edit_uri: edit/main/src/mkdocs_demo/docs
site_dir: ../../site
use_directory_urls: true
watch:
  - config/
  - docs/
  - lib/
  - scripts/
  - templates/
  - mkdocs.yml
copyright: >
  Laurens van der Tas - Copyright &copy; 2023 - 2024
  <br/><a href="#__consent" style="font-size: 0.75em; font-style: italic;">Change cookie settings</a>

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

##############
# Navigation #
##############

nav:
  - About: index.md
  - Features: features/
  - API Reference: reference/

#########
# Theme #
#########

theme:
  name: material
  language: en
  font:
    text: Barlow
    code: JetBrains Mono
  favicon: images/code-json.png
  icon:
    logo: material/code-json
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  custom_dir: docs/overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share
    - toc.follow
    - header.autohide
    - announce.dismiss
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: lime
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: lime
      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to system preference

extra_css:
  - css/mkdocstrings.css
  - css/style.css

#######################
# Markdown Extensions #
#######################

markdown_extensions:
  - abbr
  - def_list
  - attr_list
  - admonition
  - callouts
  - footnotes
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: lpvdt
      repo: mkdocs-demo
  - pymdownx.betterem
  - pymdownx.snippets:
      base_path: [!relative $config_dir]
      check_paths: true
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

###########
# Plugins #
###########

plugins:
  - offline:
      enabled: !ENV [OFFLINE, false]
  - autorefs
  - privacy:
      enabled: true
      cache: true
      assets: true
      assets_fetch: true
  - social:
      enabled: !ENV [CI, true]
      cards: true
      cards_dir: assets/images/social
  - search:
      lang: en
  - markdown-exec:
      ansi: required
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      custom_templates: templates
      default_handler: python
      enable_inventory: true
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
            - https://mkdocstrings.github.io/autorefs/objects.inv
          paths: [src]
          options:
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: list
            heading_level: 1
            inherited_members: true
            merge_init_into_class: true
            separate_signature: true
            show_root_heading: true
            show_root_full_path: true
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true
            show_submodules: true
            group_by_category: true
            show_if_no_docstring: true
  - minify:
      minify_html: !ENV [DEPLOY, true]

#########
# Extra #
#########

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/LPvdT
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/lpvdt/
  consent:
    title: Cookie consent
    description: >-
      I use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of my documentation, and whether or not users
      find what they're searching for. Your consent helps me to improve the documentation.
