repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        args:
          - --unsafe
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.15
    hooks:
      - id: ruff
        name: Ruff Linter
        types_or:
          - python
          - pyi
          - jupyter
        args:
          - --fix
      - id: ruff-format
        name: Ruff Formatter
        types_or:
          - python
          - pyi
          - jupyter

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        name: Mypy
        args:
          - --ignore-missing-imports
