name: ci-cd
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
env:
  cache_id:
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Configure Git credentials
      - run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v4
        name: Configure Python
        with:
          python-version: 3.11
      - run: echo "cache_id=$(date --utc +%V)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Install dependencies with caching
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: |
          pip install \
            mkdocs-material[imaging] \
            mkdocs-gen-files \
            mkdocs-literate-nav \
            mkdocs-minify-plugin \
            mkdocs-section-index \
            markdown-callouts \
            mkdocstrings[python] \
            markdown-exec[ansi]
      - run: |
          mkdocs gh-deploy \
            --config-file src/mkdocs_demo/mkdocs.yml \
            --clean \
            --use-directory-urls \
            --force
